package com.lemonlab.learnturkish.keys

class Keys{
    companion object {
        var SCORE = "USER_SCORE"
        var RESULT_SCORE = "RESULT"
        var QUIZ_TYPE = "QUIZ_TYPE"
        var LESSON_TYPE = "LESSON_TYPE"

        // LESSON QUIZ PASSED
        var LESSON_QUIZ_ONE = "LESSON_QUIZ_ONE"
        var LESSON_QUIZ_TWO = "LESSON_QUIZ_TWO"
        var LESSON_QUIZ_THREE = "LESSON_QUIZ_THREE"
        var LESSON_QUIZ_FOUR = "LESSON_QUIZ_FOUR"
        var LESSON_QUIZ_FIVE = "LESSON_QUIZ_FIVE"
        var LESSON_QUIZ_SIX = "LESSON_QUIZ_SIX"
        var LESSON_QUIZ_SEVEN = "LESSON_QUIZ_SEVEN"
        var LESSON_QUIZ_EIGHT = "LESSON_QUIZ_EIGHT"
        var LESSON_QUIZ_NINE = "LESSON_QUIZ_NINE"
        var LESSON_QUIZ_TEN = "LESSON_QUIZ_TEN"
        var LESSON_QUIZ_ELEVEN = "LESSON_QUIZ_ELEVEN"

        // LESSON QUIZ LOCKED
        var LESSON_QUIZ_ONE_LOCKED = "LESSON_QUIZ_ONE_LOCKED"
        var LESSON_QUIZ_TWO_LOCKED = "LESSON_QUIZ_TWO_LOCKED"
        var LESSON_QUIZ_THREE_LOCKED = "LESSON_QUIZ_THREE_LOCKED"
        var LESSON_QUIZ_FOUR_LOCKED = "LESSON_QUIZ_FOUR_LOCKED"
        var LESSON_QUIZ_FIVE_LOCKED = "LESSON_QUIZ_FIVE_LOCKED"
        var LESSON_QUIZ_SIX_LOCKED = "LESSON_QUIZ_SIX_LOCKED"
        var LESSON_QUIZ_SEVEN_LOCKED = "LESSON_QUIZ_SEVEN_LOCKED"
        var LESSON_QUIZ_EIGHT_LOCKED = "LESSON_QUIZ_EIGHT_LOCKED"
        var LESSON_QUIZ_NINE_LOCKED = "LESSON_QUIZ_NINE_LOCKED"
        var LESSON_QUIZ_TEN_LOCKED = "LESSON_QUIZ_TEN_LOCKED"
        var LESSON_QUIZ_ELEVEN_LOCKED = "LESSON_QUIZ_ELEVEN_LOCKED"
        var LESSON_CHAT_ONE_LOCKED = "LESSON_CHAT_ONE_LOCKED"
        var LESSON_QUIZ_TWELVE_LOCKED = "LESSON_QUIZ_TWELVE_LOCKED"


        var LESSON_ONE = "LESSON_ONE"
        var LESSON_TWO = "LESSON_TWO"
        var LESSON_THREE = "LESSON_THREE"
        var LESSON_FOUR = "LESSON_FOUR"
        var LESSON_FIVE = "LESSON_FIVE"
        var LESSON_SIX = "LESSON_SIX"
        var LESSON_SEVEN = "LESSON_SEVEN"
        var LESSON_EIGHT = "LESSON_EIGHT"
        var LESSON_NINE = "LESSON_NINE"
        var LESSON_TEN = "LESSON_TEN"
        var LESSON_ELEVEN = "LESSON_ELEVEN"
        var LESSON_TWELVE = "LESSON_TWELVE"
        var LESSON_THIRTEEN = "LESSON_THIRTEEN"
        var CHAT_LESSON_ONE = "CHAT_LESSON_ONE"
    }
}